imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

external:
  elasticsearchHost: elasticsearch:9200
  gearmanHost: gearmand:4730
  memcachedHost: memcached:11211
  mysqlDsn: mysql:host=mysql;dbname=atom;charset=utf8mb4
  mysqlUsername: atom
  mysqlPassword: atom

secret:
  annotations: {}

storage:
  uploads:
    existingClaim: ""
  downloads:
    existingClaim: ""

atom:
  namespace: atom
  cacheNamespace: ""
  workersKey: ""

  public:
    enabled: true
    replicaCount: 1
    annotations: {}
    podAnnotations: {}
    image:
      repository: ghcr.io/sevein/atbox-public
      tag: ""
      pullPolicy: IfNotPresent
    sessionName: ""
    service:
      annotations: {}
      type: ClusterIP
      port: 80
    resources: {}

  admin:
    enabled: false
    replicaCount: 1
    annotations: {}
    podAnnotations: {}
    image:
      repository: ghcr.io/sevein/atbox-admin
      tag: ""
      pullPolicy: IfNotPresent
    sessionName: atom-admin
    sessionCookieSecure: true
    sessionCookieSameSite: lax
    oidc:
      enabled: false
      providerUrl: ""
      clientId: ""
      clientSecret:
        existingSecret: ""
        key: client-secret
      redirectUrl: ""
      logoutRedirectUrl: ""
      sendOidcLogout: true
      enableRefreshTokenUse: true
      serverCert: "false"
      setGroupsFromAttributes: true
      scopes:
        - openid
        - profile
        - email
      rolesSource: access-token
      rolesPath:
        - realm_access
        - roles
      userMatchingSource: oidc-email
      autoCreateAtomUser: true
      userGroups:
        administrator:
          attributeValue: atom-admin
          groupId: 100
        editor:
          attributeValue: atom-editor
          groupId: 101
        contributor:
          attributeValue: atom-contributor
          groupId: 102
        translator:
          attributeValue: atom-translator
          groupId: 103
    uploads:
      enabled: false
      limit: "-1"
      postMaxSize: 512M
      uploadMaxFilesize: 512M
      maxFileUploads: "20"
    service:
      annotations: {}
      type: ClusterIP
      port: 80
    resources: {}

  worker:
    enabled: false
    replicaCount: 1
    annotations: {}
    podAnnotations: {}
    image:
      repository: ghcr.io/sevein/atbox-worker
      tag: ""
      pullPolicy: IfNotPresent
    memoryLimit: "-1"
    maxJobCount: ""
    maxMemUsage: ""
    resources: {}

bootstrap:
  searchPopulate:
    enabled: false
    annotations: {}
    podAnnotations: {}
    image:
      repository: ghcr.io/sevein/atbox-cli
      tag: ""
      pullPolicy: IfNotPresent
    backoffLimit: 1
    restartPolicy: Never
