{{- if .Values.atom.public.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "atbox.fullname" . }}-public
  labels:
    {{- include "atbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: public
  {{- with .Values.atom.public.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.atom.public.replicaCount }}
  selector:
    matchLabels:
      {{- include "atbox.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: public
  template:
    metadata:
      labels:
        {{- include "atbox.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: public
      {{- with .Values.atom.public.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: atbox
          image: "{{ .Values.atom.public.image.repository }}:{{ default .Chart.AppVersion .Values.atom.public.image.tag }}"
          imagePullPolicy: {{ .Values.atom.public.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          {{- if or .Values.storage.uploads.existingClaim .Values.storage.downloads.existingClaim }}
          volumeMounts:
            {{- if .Values.storage.uploads.existingClaim }}
            - name: uploads
              mountPath: /atom/src/web/uploads
              readOnly: true
            {{- end }}
            {{- if .Values.storage.downloads.existingClaim }}
            - name: downloads
              mountPath: /atom/src/web/downloads
              readOnly: true
            {{- end }}
          {{- end }}
          env:
            {{- include "atbox.commonEnv" . | nindent 12 }}
            - name: ATOM_SESSION_NAME
              value: {{ default .Values.atom.namespace .Values.atom.public.sessionName | quote }}
          {{- include "atbox.podSecurityContext" . | nindent 10 }}
          {{- with .Values.atom.public.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if or .Values.storage.uploads.existingClaim .Values.storage.downloads.existingClaim }}
      volumes:
        {{- if .Values.storage.uploads.existingClaim }}
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ .Values.storage.uploads.existingClaim | quote }}
        {{- end }}
        {{- if .Values.storage.downloads.existingClaim }}
        - name: downloads
          persistentVolumeClaim:
            claimName: {{ .Values.storage.downloads.existingClaim | quote }}
        {{- end }}
      {{- end }}
{{- end }}
