{{- if .Values.bootstrap.searchPopulate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "atbox.fullname" . }}-search-populate
  labels:
    {{- include "atbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: lifecycle
  {{- with .Values.bootstrap.searchPopulate.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: {{ .Values.bootstrap.searchPopulate.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "atbox.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: lifecycle
      {{- with .Values.bootstrap.searchPopulate.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: {{ .Values.bootstrap.searchPopulate.restartPolicy }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: search-populate
          image: "{{ .Values.bootstrap.searchPopulate.image.repository }}:{{ default .Chart.AppVersion .Values.bootstrap.searchPopulate.image.tag }}"
          imagePullPolicy: {{ .Values.bootstrap.searchPopulate.image.pullPolicy }}
          command: ["php", "symfony", "search:populate"]
          env:
            {{- include "atbox.commonEnv" . | nindent 12 }}
            - name: ATOM_SESSION_NAME
              value: {{ .Values.atom.namespace | quote }}
          {{- include "atbox.podSecurityContext" . | nindent 10 }}
{{- end }}
