apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atbox.fullname" . }}-database
  labels:
    {{- include "atbox.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  mysql-dsn: {{ .Values.external.mysqlDsn | quote }}
  mysql-username: {{ .Values.external.mysqlUsername | quote }}
  mysql-password: {{ .Values.external.mysqlPassword | quote }}
